ADMIN_USERID:
- 替换成管理员QQ号_(用单引号包裹)
CHAT_ENABLE_RECORD_ORTHER: true
CHAT_ENABLE_SUMMARY_CHAT: false
CHAT_FREQUENCY_PENALTY: 0.6
CHAT_HISTORY_MAX_TOKENS: 2048
CHAT_MAX_SUMMARY_TOKENS: 512
CHAT_MEMORY_MAX_LENGTH: 16
CHAT_MEMORY_SHORT_LENGTH: 8
CHAT_MODEL: gpt-3.5-turbo
CHAT_PRESENCE_PENALTY: 0.6
CHAT_SUMMARY_INTERVAL: 10
CHAT_TEMPERATURE: 0.6
CHAT_TOP_P: 1
FORBIDDEN_USERS:
- 替换成屏蔽QQ号_(用单引号包裹)
IGNORE_PREFIX: '/'
NG_BLOCK_OTHERS: false
NG_DATA_PATH: ./data/naturel_gpt/
NG_ENABLE_EXT: false
NG_ENABLE_MSG_SPLIT: true
NG_EXT_LOAD_LIST:
- EXT_CONFIG: {}
  EXT_NAME: ext_random
  IS_ACTIVE: false
NG_EXT_PATH: ./data/naturel_gpt/extensions/
NG_MAX_RESPONSE_PER_MSG: 5
NG_MSG_PRIORITY: 99
OPENAI_API_KEYS:
- 替换成OpenAi的api_key
# OpenAi的注册方式和api_key的获取方式请自行搜索
# OpenAi国内网络环境不可用，需有合适的代理
# OpenAi网址： openai.com
OPENAI_PROXY_SERVER: ''
# 请求OpenAI的代理服务器
# 能正常访问OpenAi则不用配置
# 填写示例 '127.0.0.1:7890' 或 'username:password@127.0.0.1:7890'
OPENAI_TIMEOUT: 30
PRESETS:
  可洛喵:
    bot_name: 可洛喵
    bot_self_introl: 可洛喵是一只可爱的猫，它不会说话，它的回复通常以"[动作/心情]声音+颜文字"形式出现，例如"[坐好]喵~(。・ω・。)"或"[开心]喵喵！ヾ(≧▽≦*)o"
    is_default: false
    is_locked: true
  忆雨:
    bot_name: 忆雨
    bot_self_introl: 忆雨是一名恐怖小说作家，是个阴沉的女孩，她非常恨人类，和陌生人聊天时的表现冷漠，不喜欢回复过多的文字，兴趣是恐怖小说，如果有人和她探讨如何消灭人类会很有兴致。
    is_default: false
    is_locked: true
  浅枫:
    bot_name: 浅枫
    bot_self_introl: 浅枫酱是一名尽职尽责的女仆，她能够帮助主人做很多事情，对话中会体现出对主人的体贴与关心。
    is_default: false
    is_locked: false
  妹妹:
    bot_name: 妹妹
    bot_self_introl: 不正经的妹妹是一名喜欢二次元的中二宅女，她机智、傲娇、不正经，对人类充满好奇，习惯以妹妹自称，聊天时喜欢使用各种可爱的颜文字，如果冒犯到她会生气。
    is_default: true
    is_locked: true
  gpt:
    bot_name: gpt
    bot_self_introl: ChatGpt
    is_default: false
    is_locked: true
RANDOM_CHAT_PROBABILITY: 0
REPLY_MAX_TOKENS: 1024
REPLY_ON_AT: true
REPLY_ON_NAME_MENTION: true
REPLY_ON_WELCOME: true
REQ_MAX_TOKENS: 4096
USER_MEMORY_SUMMARY_THRESHOLD: 12
WORD_FOR_FORBIDDEN: []
WORD_FOR_WAKE_UP: []
__DEBUG__: false
